apiVersion: nais.io/v1
kind: Naisjob
metadata:
  labels:
    team: dvh-analytisk-plattform
  name: pxpyfactory-job
  namespace: dvh-analytisk-plattform
spec:
  image: "{{ image }}"
  # schedule: "*/5 6-16 * * 1-5"  # Commented out to run once on deployment only
  gcp:
    buckets:
      - name: pxweb2-api-nais-px
        cascadingDelete: false
        lifecycleCondition:
          age: 7
          createdBefore: 2020-01-01
          daysSinceCustomTime: 2
          numNewerVersions: 2
          withState: ANY