name: Deploy px creator and run

on:
  push:
    branches: [main_off]
  workflow_dispatch:
    inputs:
      environment:
        description: 'Environment to deploy'
        type: choice
        required: true
        default: 'dev'
        options:
          - dev
          - prod

permissions:
  contents: read
  id-token: write

jobs:
  build-and-push:
    name: Build and push GAR
    runs-on: ubuntu-latest
    outputs:
      image: ${{ steps.docker-build-push.outputs.image }}
    steps:
      - uses: actions/checkout@v4
      - name: Push docker image to GAR
        uses: nais/docker-build-push@v0
        id: docker-build-push
        with:
          team: statistikkbank
          salsa: true

  deploy:
    name: Deploy px creator to - ${{ github.event.inputs.environment || 'dev' }}
    runs-on: ubuntu-latest
    environment: ${{ github.event.inputs.environment || 'dev' }}
    needs: [build-and-push]
    steps:
      - uses: actions/checkout@v4
      - name: Deploy-
        uses: nais/deploy/actions/deploy@v2
        env:
          CLUSTER: ${{ vars.DEPLOYMENT_CLUSTER }}
          RESOURCE: naisjob.yaml
          VAR: image=${{ needs.build-and-push.outputs.image }}